# Generated by Django 4.0.4 on 2022-05-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Дата пары'),
        ),
    ]
