# Generated by Django 4.0.4 on 2022-06-14 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0002_timetable_remote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='remote',
        ),
    ]
