# Generated by Django 4.0.4 on 2022-06-14 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0004_alter_timetable_cabinet_alter_timetable_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='cabinet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schedule.cabinet', verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schedule.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schedule.lesson', verbose_name='Занятие'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='subgroups',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schedule.subgroups', verbose_name='Подгруппы'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schedule.teacher', verbose_name='Преподаватель'),
        ),
    ]
